version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/javascript"
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    groups:
      javascript-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "bundler"
    directory: "/ruby"
    versioning-strategy: "lockfile-only"
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Tokyo"
    groups:
      ruby-dependencies:
        patterns:
          - "*"
